name: Build and Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: rlespinasse/github-slug-action@v4
      if: ${{ github.event_name != 'release' }}
      with:
        short-length: 4

    - uses: nyetwurk/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'release' }}
      with:
        name: trim-heatmap-${{ env.GITHUB_SHA_SHORT }}-win
        path: src/dist/windows
        overwrite: true

    - name: Upload Artifact to Release
      if: github.event_name == 'release' && github.event.action == 'created'
      run: |
        cd src/dist/windows
        zip -qr trim-heatmap-${{ github.ref_name }}-win.zip .
        gh release upload ${{ github.ref_name }} trim-heatmap-${{ github.ref_name }}-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
