name: Build and Release
on:
  push:
  pull_request:
  release:
    types: [ published ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        cd src
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd src
        python heatmap.py --test

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'release'
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: rlespinasse/github-slug-action@v4
      if: ${{ github.event_name != 'release' }}
      with:
        short-length: 4

    - uses: nyetwurk/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'release' }}
      with:
        name: trim-heatmap-${{ env.GITHUB_SHA_SHORT }}-win
        path: src/dist/windows
        overwrite: true

    - name: Upload Artifact to Release
      if: github.event_name == 'release' && github.event.action == 'published'
      run: |
        cd src/dist/windows
        zip -qr trim-heatmap-${{ github.ref_name }}-win.zip .
        gh release upload --clobber ${{ github.ref_name }} trim-heatmap-${{ github.ref_name }}-win.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
